# Generated by Django 6.0.7 on 2026-08-09 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0005_movie_tmdb_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('amount_paise', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='movies.theater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('confirmed', 'Confirmed'), ('released', 'Released'), ('expired', 'Expired')], default='active', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='bookings.paymentorder')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='movies.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('payment_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='bookings.paymentorder')),
            ],
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', 'expires_at'], name='bookings_pa_status_5b6d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['user', 'status'], name='bookings_pa_user_id_fdb5f3_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['seat', 'status', 'expires_at'], name='bookings_se_seat_id_eebaf2_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['payment_order', 'status'], name='bookings_se_payment_af63eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='seatreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('seat',), name='unique_active_seat_reservation'),
        ),
    ]
