# Generated by Django 6.0.7 on 2026-08-09 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('movies', '0005_movie_tmdb_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.paymentorder'),
        ),
    ]
