# Generated by Django 6.0.7 on 2026-09-05 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_paymentorder_paid_at_and_more'),
        ('movies', '0006_booking_payment_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at'], name='movies_book_booked__a7ab7e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['movie', 'booked_at'], name='movies_book_movie_i_323598_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['theater', 'booked_at'], name='movies_book_theater_a2fd03_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_order'], name='movies_book_payment_d1ef21_idx'),
        ),
    ]
